### ISSUE TITLE
Metodos para ejecutar sentencias

### ISSUE THREAD

**Issue by FrontDevAngel** [JorgeMont/Calculator_Globant-Bootcamp#1]
https://github.com/JorgeMont/Calculator_Globant-Bootcamp/blob/5eee8512cd5b687b64bbdf8c9d1d368ca0b9fc57/app.js#L6-L30

Crees que esto se pueda mejorar con un `switch` ? 😃

**Comment by JorgeMont** [comment]
@FrontDevAngel Muchas gracias por la observación, ya lo implemente. También agregue la mejora de que después de hacer una operación ya no es necesario borrar la anterior, se hace automáticamente.
